### ISSUE TITLE
Adding Name to Bike Check-in/out

### ISSUE THREAD

**Issue by meredithshores** [GOLewis-McChord/go_src#2]
Product: django
Source: Bike check-in/out
Goal: Add full name, email, and contact info to the check in outs
Error: forgot how to add missing section
Description: I checked my notes but I didn't document the commands and where to open/insert info for adding sections to the app on any specific form. This one would be getting all the pertinent information fields added to the check in outs form under bike.

**Comment by mlockwood** [comment]
In here:
https://github.com/GOLewis-McChord/go_src/tree/master/apps/go_django/bike

Edit models by adding a new field for what you need. Then do the migration because this is a change to the model.

Before any data is entered modify the serializers in that same folder to add the new field.

Although I know there was discussion about hiring a consultant to manage this. Maybe they should be the ones worrying about this? I am not sure what the business need is for the data at this time.

I am going to leave this issue open through the end of the week. Let me know if you still need help by then otherwise I will go ahead and close it.
